# Generated by Django 6.0.4 on 2026-04-27 04:50

import course_app.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=course_app.models.lesson_video_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi', 'mkv', 'webm'])])),
                ('duration', models.PositiveIntegerField(default=0, help_text='Sekundlarda')),
                ('size', models.PositiveBigIntegerField(default=0, help_text='Baytlarda')),
                ('is_processed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='course_app.lesson')),
            ],
        ),
    ]
